# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrowdstrikeFalconDownloader < Formula
  desc "CLI/TUI for downloading sensors for CrowdStrike Falcon."
  homepage "https://github.com/northwood-labs/crowdstrike-falcon-downloader"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0/crowdstrike-falcon-downloader-1.0.0-darwin-universal.zip", using: CurlDownloadStrategy,
      headers: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
      ]
    sha256 "7baca4b48c836340713d5fa78955e247e9c5caa36a5fb06269e57f6eee15d16b"

    def install
      bin.install "crowdstrike-falcon-downloader"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0/crowdstrike-falcon-downloader-1.0.0-linux-amd64.zip", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "b78b6f8df034fd84a58c78bc2779b78bb356e6727ad3f4e264255c9485874a8c"

      def install
        bin.install "crowdstrike-falcon-downloader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0/crowdstrike-falcon-downloader-1.0.0-linux-arm64.zip", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "92f35b948d87a5fa0a60e3aadcaf727a65695dd531f00061dc4355b4eee20ee4"

      def install
        bin.install "crowdstrike-falcon-downloader"
      end
    end
  end

  def caveats
    <<~EOS
      This is a macOS Universal Binary that should work on Intel and Apple Silicon chips.
    EOS
  end

  test do
    system "#{bin}/crowdstrike-falcon-downloader version"
  end
end
