# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrowdstrikeFalconDownloader < Formula
  desc "CLI/TUI for downloading sensors for CrowdStrike Falcon."
  homepage "https://github.com/northwood-labs/crowdstrike-falcon-downloader"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0/crowdstrike-falcon-downloader-1.0.0-darwin-universal.zip", using: CurlDownloadStrategy,
      headers: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
      ]
    sha256 "ceed1ffd6674da7276f5c9e5fa21eea8bf77b90ac21a11524aa71e53398bc099"

    def install
      bin.install "crowdstrike-falcon-downloader"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0/crowdstrike-falcon-downloader-1.0.0-linux-amd64.zip", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "2133d6935446a559eefc8a546df5a90e4ad47c9c8971264d6b4ef685d9e39a92"

      def install
        bin.install "crowdstrike-falcon-downloader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0/crowdstrike-falcon-downloader-1.0.0-linux-arm64.zip", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "8999c8bfe7f5ec5c1216eeadf68795846f0a16716190d47a5ac493b383697e45"

      def install
        bin.install "crowdstrike-falcon-downloader"
      end
    end
  end

  def caveats
    <<~EOS
      This is a macOS Universal Binary that should work on Intel and Apple Silicon chips.
    EOS
  end

  test do
    system "#{bin}/crowdstrike-falcon-downloader version"
  end
end
