# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrowdstrikeFalconDownloader < Formula
  desc "CLI/TUI for downloading sensors for CrowdStrike Falcon."
  homepage "https://github.com/northwood-labs/crowdstrike-falcon-downloader"
  version "1.0.0-rc9"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0-rc9/crowdstrike-falcon-downloader-1.0.0-rc9-darwin-universal.zip", using: CurlDownloadStrategy,
      headers: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
      ]
    sha256 "d22d3693cb598a1705b1269a5665dda7a513252f9752e885c067edbf3bce4a62"

    def install
      bin.install "crowdstrike-falcon-downloader"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0-rc9/crowdstrike-falcon-downloader-1.0.0-rc9-linux-amd64.zip", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "42500fae5c56e142fa8eb8920b240fd14357576699d45f41a382e88eafedb891"

      def install
        bin.install "crowdstrike-falcon-downloader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwood-labs/crowdstrike-falcon-downloader/releases/download/1.0.0-rc9/crowdstrike-falcon-downloader-1.0.0-rc9-linux-arm64.zip", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: Bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "2f69157e81cf2ca02c1af9f4c1c9d87005123c0a7dc795138f2353a4ed5f6a77"

      def install
        bin.install "crowdstrike-falcon-downloader"
      end
    end
  end

  def caveats
    <<~EOS
      This is a macOS Universal Binary that should work on Intel and Apple Silicon chips.
    EOS
  end

  test do
    system "#{bin}/crowdstrike-falcon-downloader version"
  end
end
